# Generated by Django 3.0.10 on 2020-11-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_products',
            field=models.ManyToManyField(blank=True, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
