# Generated by Django 3.0.10 on 2020-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201205_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
