# Generated by Django 3.0.10 on 2021-02-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201217_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_img',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='is_img'),
        ),
    ]
