# Generated by Django 3.0.10 on 2021-02-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_img',
            field=models.ImageField(blank=True, null=True, upload_to='is_img', verbose_name='is_img'),
        ),
    ]
