# Generated by Django 3.0.10 on 2021-02-06 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210206_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIsImg',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'is_img',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_img',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='is_img', verbose_name='is_img'),
        ),
    ]
