# Generated by Django 3.0.10 on 2021-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0004_product_like'),
        ('social_django', '0010_uid_db_index'),
        ('account', '0002_email_max_length'),
        ('users', '0008_auto_20210206_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIsImg',
        ),
    ]
