# Generated by Django 3.0.10 on 2021-02-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210217_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpointhistory',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
