# Generated by Django 3.0.10 on 2021-02-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210217_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpointhistory',
            old_name='point',
            new_name='point_history',
        ),
    ]
