# Generated by Django 3.0.10 on 2021-02-21 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210217_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpointhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpointhistory',
            name='point_history',
            field=models.PositiveIntegerField(verbose_name='User point this time'),
        ),
    ]
