branch-defaults:
  master:
    environment: Djamazon2-dev
    group_suffix: null
global:
  application_name: Djamazon2
  branch: null
  default_ec2_keyname: aws-eb-djamazon2
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application