# Generated by Django 3.0.10 on 2020-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Product unit price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='subtotal'),
        ),
    ]
