# Generated by Django 3.0.10 on 2021-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210223_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
