# Generated by Django 3.0.10 on 2021-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210223_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
