# Generated by Django 3.0.10 on 2021-03-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210223_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
