# Generated by Django 3.0.10 on 2021-03-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210226_1535'),
        ('app', '0011_auto_20210310_1243'),
    ]

    operations = [
    ]
